export const fillIcons = [
    "AddressBookFill",
    "AlipayCircleFill",
    "AlipaySquareFill",
    "AudioFill",
    "CheckCircleFill",
    "CheckShieldFill",
    "ClockCircleFill",
    "CloseCircleFill",
    "DownFill",
    "EditFill",
    "EditSFill",
    "ExclamationCircleFill",
    "ExclamationShieldFill",
    "EyeFill",
    "EyeInvisibleFill",
    "FireFill",
    "ForbidFill",
    "FrownFill",
    "HeartFill",
    "InformationCircleFill",
    "KoubeiFill",
    "LocationFill",
    "LockFill",
    "MailFill",
    "MessageFill",
    "PhoneFill",
    "PhonebookFill",
    "QuestionCircleFill",
    "SmileFill",
    "SoundMuteFill",
    "StarFill",
    "TeamFill"
];

export const AddressBookFill=$r('app.media.AddressBookFill');
export const AlipayCircleFill=$r('app.media.AlipayCircleFill');
export const AlipaySquareFill=$r('app.media.AlipaySquareFill');
export const AudioFill=$r('app.media.AudioFill');
export const CheckCircleFill=$r('app.media.CheckCircleFill');
export const CheckShieldFill=$r('app.media.CheckShieldFill');
export const ClockCircleFill=$r('app.media.ClockCircleFill');
export const CloseCircleFill=$r('app.media.CloseCircleFill');
export const DownFill=$r('app.media.DownFill');
export const EditFill=$r('app.media.EditFill');
export const EditSFill=$r('app.media.EditSFill');
export const ExclamationCircleFill=$r('app.media.ExclamationCircleFill');
export const ExclamationShieldFill=$r('app.media.ExclamationShieldFill');
export const EyeFill=$r('app.media.EyeFill');
export const EyeInvisibleFill=$r('app.media.EyeInvisibleFill');
export const FireFill=$r('app.media.FireFill');
export const ForbidFill=$r('app.media.ForbidFill');
export const FrownFill=$r('app.media.FrownFill');
export const HeartFill=$r('app.media.HeartFill');
export const InformationCircleFill=$r('app.media.InformationCircleFill');
export const KoubeiFill=$r('app.media.KoubeiFill');
export const LocationFill=$r('app.media.LocationFill');
export const LockFill=$r('app.media.LockFill');
export const MailFill=$r('app.media.MailFill');
export const MessageFill=$r('app.media.MessageFill');
export const PhoneFill=$r('app.media.PhoneFill');
export const PhonebookFill=$r('app.media.PhonebookFill');
export const QuestionCircleFill=$r('app.media.QuestionCircleFill');
export const SmileFill=$r('app.media.SmileFill');
export const SoundMuteFill=$r('app.media.SoundMuteFill');
export const StarFill=$r('app.media.StarFill');
export const TeamFill=$r('app.media.TeamFill');

