
export const icons = [
    "AaOutline", "AddCircleOutline", "AddOutline", "AddSquareOutline", "AntOutline", "AppOutline", "AppstoreOutline", 
    "ArrowDownCircleOutline", "ArrowsAltOutline", "AudioMutedOutline", "AudioOutline", "BankcardOutline", "BellMuteOutline", 
    "BellOutline", "BillOutline", "CalculatorOutline", "CalendarOutline", "CameraOutline", "ChatAddOutline", "ChatCheckOutline", 
    "ChatWrongOutline", "CheckCircleOutline", "CheckOutline", "CheckShieldOutline", "ClockCircleOutline", "CloseCircleOutline", 
    "CloseOutline", "CloseShieldOutline", "CollectMoneyOutline", "CompassOutline", "ContentOutline", "CouponOutline", 
    "DeleteOutline", "DownCircleOutline", "DownOutline", "DownlandOutline", "EditSOutline", "EnvironmentOutline", 
    "ExclamationCircleOutline", "ExclamationOutline", "ExclamationShieldOutline", "ExclamationTriangleOutline", 
    "EyeInvisibleOutline", "EyeOutline", "FaceRecognitionOutline", "FileOutline", "FileWrongOutline", "FillinOutline", 
    "FilterOutline", "FingerdownOutline", "FlagOutline", "FolderOutline", "FrownOutline", "GiftOutline", "GlobalOutline", 
    "HandPayCircleOutline", "HeartOutline", "HistogramOutline", "InformationCircleOutline", "KeyOutline", "KoubeiOutline", 
    "LeftOutline", "LikeOutline", "LinkOutline", "LocationOutline", "LockOutline", "LoopOutline", "MailOpenOutline", 
    "MailOutline", "MessageOutline", "MinusCircleOutline", "MinusOutline", "MoreOutline", "MovieOutline", "PayCircleOutline", 
    "PhonebookOutline", "PictureOutline", "PictureWrongOutline", "PicturesOutline", "PieOutline", "PlayOutline", 
    "QuestionCircleOutline", "ReceiptOutline", "ReceivePaymentOutline", "RedoOutline", "RightOutline", "ScanCodeOutline", 
    "ScanningFaceOutline", "ScanningOutline", "SearchOutline", "SendOutline", "SetOutline", "ShopbagOutline", "ShrinkOutline", 
    "SmileOutline", "SoundMuteOutline", "SoundOutline", "StarOutline", "StopOutline", "SystemQRcodeOutline", "TagOutline", 
    "TeamOutline", "TextDeletionOutline", "TextOutline", "TransportQRcodeOutline", "TravelOutline", "TruckOutline", 
    "UndoOutline", "UnlockOutline", "UnorderedListOutline", "UpCircleOutline", "UpOutline", "UploadOutline", "UserAddOutline", 
    "UserCircleOutline", "UserContactOutline", "UserOutline", "UserSetOutline", "VideoOutline"
];

export const AaOutline=$r('app.media.AaOutline');
export const AddCircleOutline=$r('app.media.AddCircleOutline');
export const AddOutline=$r('app.media.AddOutline');
export const AddSquareOutline=$r('app.media.AddSquareOutline');
export const AntOutline=$r('app.media.AntOutline');
export const AppOutline=$r('app.media.AppOutline');
export const AppstoreOutline=$r('app.media.AppstoreOutline');
export const ArrowDownCircleOutline=$r('app.media.ArrowDownCircleOutline');
export const ArrowsAltOutline=$r('app.media.ArrowsAltOutline');
export const AudioMutedOutline=$r('app.media.AudioMutedOutline');
export const AudioOutline=$r('app.media.AudioOutline');
export const BankcardOutline=$r('app.media.BankcardOutline');
export const BellMuteOutline=$r('app.media.BellMuteOutline');
export const BellOutline=$r('app.media.BellOutline');
export const BillOutline=$r('app.media.BillOutline');
export const CalculatorOutline=$r('app.media.CalculatorOutline');
export const CalendarOutline=$r('app.media.CalendarOutline');
export const CameraOutline=$r('app.media.CameraOutline');
export const ChatAddOutline=$r('app.media.ChatAddOutline');
export const ChatCheckOutline=$r('app.media.ChatCheckOutline');
export const ChatWrongOutline=$r('app.media.ChatWrongOutline');
export const CheckCircleOutline=$r('app.media.CheckCircleOutline');
export const CheckOutline=$r('app.media.CheckOutline');
export const CheckShieldOutline=$r('app.media.CheckShieldOutline');
export const ClockCircleOutline=$r('app.media.ClockCircleOutline');
export const CloseCircleOutline=$r('app.media.CloseCircleOutline');
export const CloseOutline=$r('app.media.CloseOutline');
export const CloseShieldOutline=$r('app.media.CloseShieldOutline');
export const CollectMoneyOutline=$r('app.media.CollectMoneyOutline');
export const CompassOutline=$r('app.media.CompassOutline');
export const ContentOutline=$r('app.media.ContentOutline');
export const CouponOutline=$r('app.media.CouponOutline');
export const DeleteOutline=$r('app.media.DeleteOutline');
export const DownCircleOutline=$r('app.media.DownCircleOutline');
export const DownOutline=$r('app.media.DownOutline');
export const DownlandOutline=$r('app.media.DownlandOutline');
export const EditSOutline=$r('app.media.EditSOutline');
export const EnvironmentOutline=$r('app.media.EnvironmentOutline');
export const ExclamationCircleOutline=$r('app.media.ExclamationCircleOutline');
export const ExclamationOutline=$r('app.media.ExclamationOutline');
export const ExclamationShieldOutline=$r('app.media.ExclamationShieldOutline');
export const ExclamationTriangleOutline=$r('app.media.ExclamationTriangleOutline');
export const EyeInvisibleOutline=$r('app.media.EyeInvisibleOutline');
export const EyeOutline=$r('app.media.EyeOutline');
export const FaceRecognitionOutline=$r('app.media.FaceRecognitionOutline');
export const FileOutline=$r('app.media.FileOutline');
export const FileWrongOutline=$r('app.media.FileWrongOutline');
export const FillinOutline=$r('app.media.FillinOutline');
export const FilterOutline=$r('app.media.FilterOutline');
export const FingerdownOutline=$r('app.media.FingerdownOutline');
export const FlagOutline=$r('app.media.FlagOutline');
export const FolderOutline=$r('app.media.FolderOutline');
export const FrownOutline=$r('app.media.FrownOutline');
export const GiftOutline=$r('app.media.GiftOutline');
export const GlobalOutline=$r('app.media.GlobalOutline');
export const HandPayCircleOutline=$r('app.media.HandPayCircleOutline');
export const HeartOutline=$r('app.media.HeartOutline');
export const HistogramOutline=$r('app.media.HistogramOutline');
export const InformationCircleOutline=$r('app.media.InformationCircleOutline');
export const KeyOutline=$r('app.media.KeyOutline');
export const KoubeiOutline=$r('app.media.KoubeiOutline');
export const LeftOutline=$r('app.media.LeftOutline');
export const LikeOutline=$r('app.media.LikeOutline');
export const LinkOutline=$r('app.media.LinkOutline');
export const LocationOutline=$r('app.media.LocationOutline');
export const LockOutline=$r('app.media.LockOutline');
export const LoopOutline=$r('app.media.LoopOutline');
export const MailOpenOutline=$r('app.media.MailOpenOutline');
export const MailOutline=$r('app.media.MailOutline');
export const MessageOutline=$r('app.media.MessageOutline');
export const MinusCircleOutline=$r('app.media.MinusCircleOutline');
export const MinusOutline=$r('app.media.MinusOutline');
export const MoreOutline=$r('app.media.MoreOutline');
export const MovieOutline=$r('app.media.MovieOutline');
export const PayCircleOutline=$r('app.media.PayCircleOutline');
export const PhonebookOutline=$r('app.media.PhonebookOutline');
export const PictureOutline=$r('app.media.PictureOutline');
export const PictureWrongOutline=$r('app.media.PictureWrongOutline');
export const PicturesOutline=$r('app.media.PicturesOutline');
export const PieOutline=$r('app.media.PieOutline');
export const PlayOutline=$r('app.media.PlayOutline');
export const QuestionCircleOutline=$r('app.media.QuestionCircleOutline');
export const ReceiptOutline=$r('app.media.ReceiptOutline');
export const ReceivePaymentOutline=$r('app.media.ReceivePaymentOutline');
export const RedoOutline=$r('app.media.RedoOutline');
export const RightOutline=$r('app.media.RightOutline');
export const ScanCodeOutline=$r('app.media.ScanCodeOutline');
export const ScanningFaceOutline=$r('app.media.ScanningFaceOutline');
export const ScanningOutline=$r('app.media.ScanningOutline');
export const SearchOutline=$r('app.media.SearchOutline');
export const SendOutline=$r('app.media.SendOutline');
export const SetOutline=$r('app.media.SetOutline');
export const ShopbagOutline=$r('app.media.ShopbagOutline');
export const ShrinkOutline=$r('app.media.ShrinkOutline');
export const SmileOutline=$r('app.media.SmileOutline');
export const SoundMuteOutline=$r('app.media.SoundMuteOutline');
export const SoundOutline=$r('app.media.SoundOutline');
export const StarOutline=$r('app.media.StarOutline');
export const StopOutline=$r('app.media.StopOutline');
export const SystemQRcodeOutline=$r('app.media.SystemQRcodeOutline');
export const TagOutline=$r('app.media.TagOutline');
export const TeamOutline=$r('app.media.TeamOutline');
export const TextDeletionOutline=$r('app.media.TextDeletionOutline');
export const TextOutline=$r('app.media.TextOutline');
export const TransportQRcodeOutline=$r('app.media.TransportQRcodeOutline');
export const TravelOutline=$r('app.media.TravelOutline');
export const TruckOutline=$r('app.media.TruckOutline');
export const UndoOutline=$r('app.media.UndoOutline');
export const UnlockOutline=$r('app.media.UnlockOutline');
export const UnorderedListOutline=$r('app.media.UnorderedListOutline');
export const UpCircleOutline=$r('app.media.UpCircleOutline');
export const UpOutline=$r('app.media.UpOutline');
export const UploadOutline=$r('app.media.UploadOutline');
export const UserAddOutline=$r('app.media.UserAddOutline');
export const UserCircleOutline=$r('app.media.UserCircleOutline');
export const UserContactOutline=$r('app.media.UserContactOutline');
export const UserOutline=$r('app.media.UserOutline');
export const UserSetOutline=$r('app.media.UserSetOutline');
export const VideoOutline=$r('app.media.VideoOutline');
